# Generated by Django 5.0.2 on 2024-02-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
