# Generated by Django 5.0.2 on 2024-02-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmodel',
            name='index',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
