# Generated by Django 5.0.2 on 2024-02-07 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_stockmodel_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockmodel',
            old_name='index',
            new_name='id',
        ),
    ]
